-- Affichez le numéro du billet, le prénom et le nom du client ainsi que le train (même format que pour le rapport 5) pour les billets de première classe ayant étéréservés par les clients de moins de 25 ans.
-- Ne récupérez que les informations sur les réservations payées qui ont étéfaites 20 jours avant la date de départ du train.
-- Ne prenez en compte que les trains qui partent entre le 15/04/2019 et le 25/04/2019.
-- Triez les résultats par la date de la réservation.